language: node_js

node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13

services:
  - mongodb

install:
  - npm install
  - npm install lerna -g

script:
  - npm run deps
  - npm run build
  - npm test

after_success: npm run codeclimate
