language: node_js

node_js:
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12

services:
  - mongodb

install:
  - npm install
  - npm install lerna -g

script:
  - npm run deps
  - npm run build
  - npm run test:coverage

after_success: CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN npm run codeclimate
